//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisment
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<bool> IsPremium { get; set; }
        public Nullable<int> CapacityID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> FuelTypeID { get; set; }
        public int SpeedBoxeId { get; set; }
        public Nullable<System.DateTime> ProductionYear { get; set; }
        public Nullable<decimal> Milage { get; set; }
        public string GeneralInfo { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CarModel { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual EngineCapacity EngineCapacity { get; set; }
        public virtual Model Model { get; set; }
        public virtual Color Color { get; set; }
        public virtual Fueltype Fueltype { get; set; }
        public virtual SpeedBox SpeedBox { get; set; }
        public virtual User User { get; set; }
        public virtual Advertisment Advertisments1 { get; set; }
        public virtual Advertisment Advertisment1 { get; set; }
        public virtual Advertisment Advertisments11 { get; set; }
        public virtual Advertisment Advertisment2 { get; set; }
        public virtual Advertisment Advertisments12 { get; set; }
        public virtual Advertisment Advertisment3 { get; set; }
        public virtual City City { get; set; }
    }
}
